@startuml Diagrama de sequência
actor Vibration_System
participant accelerometer

Vibration_System -> acquisition_subsystem: Iniciar aquisição de dados
Vibration_System -> processing_subsystem: Iniciar o processamento de dados
Vibration_System -> communication_subsystem: Iniciar o envio de dados
activate acquisition_subsystem
par
loop cada 2ms
    acquisition_subsystem -> accelerometer: Solicitar dados
    activate accelerometer
    accelerometer --> acquisition_subsystem: Retorna dados adquiridos
    deactivate accelerometer    
    acquisition_subsystem -> processing_queue: Coloca dados na fila de processamento
end
deactivate acquisition_subsystem
    loop cada 2ms
        processing_subsystem -> processing_queue: Retirar dados de processamento
        activate processing_subsystem
        processing_queue --> processing_subsystem: Dados adquiridos
        processing_subsystem -> processing_subsystem: Processa dados
        processing_subsystem -> sending_queue: Coloca dados processados na fila de envio
        deactivate processing_subsystem
    end

    loop cada 10ms
        communication_subsystem -> sending_queue: Retirar dados da fila de envio
        activate communication_subsystem
        sending_queue --> communication_subsystem: Dados processados
        communication_subsystem -> mqtt: Envia dados para o servidor
        activate mqtt
        mqtt --> communication_subsystem: Confirmação de envio
        deactivate mqtt
        deactivate communication_subsystem
    end
end
@enduml