@startuml Diagrama de estados
[*] -right-> initDevice

state "StartingDevice" as initDevice {
    initDevice: entry / _vibration_system->initSubsystems()
}
initDevice -right-> aguardadoColeta: Subsistemas inicializados com sucesso

state "AwaitingMonitoring" as aguardadoColeta {
    aguardadoColeta: entry / _vibration_system->startActiveDetection()
    aguardadoColeta: do / _vibration_system->getIsActive()
    aguardadoColeta: exit / _vibration_system->stopActiveDetection()
}
aguardadoColeta -> coletandoDados: Vibração detectada [getIsActive() == true]
aguardadoColeta -> aguardadoColeta: Vibração não detectada [getIsActive() == false]

state "Monitoring" as coletandoDados {
    coletandoDados: entry / _vibration_system->startMonitoringRoutines()
    coletandoDados: entry / _vibration_system->startInactiveDetection()
    coletandoDados: exit / _vibration_system->stopMonitoringRoutines()
    coletandoDados: exit / _vibration_system->stopInactiveDetection()
}
coletandoDados -down-> aguardadoColeta: Inatividade detectada [getIsInactive() == true]
coletandoDados -> coletandoDados: Inatividade não detectada [getIsInactive() == false]
@enduml